_mail/urls.py
from django.conf.urls import url
from _mail import views 

urlpatterns = [ 
  # The home view ('/tutorial/') 
  url(r'^m/$', views.home, name='home'), 
  # Explicit home ('/tutorial/home/') 
  url(r'^m/home/$', views.home, name='home'), 
  # Redirect to get token ('/tutorial/gettoken/')
  url(r'^m/gettoken/$', views.gettoken, name='gettoken'),
  # Mail view ('/tutorial/mail/')
  url(r'^m/mail/$', views.mail, name='mail'),
]

_billing/models.py
# coding=UTF-8

from calendar import monthrange
from datetime import timedelta
import datetime
import sys 
import traceback

from django.contrib.auth.models import User
from django.db import models

from _user.models import Person


# #CHANGED
# class Product(models.Model):
# 	name = models.CharField(max_length=200)
# 	price = models.DecimalField("Preis", max_digits=15, decimal_places=2, blank=True, null=True)
class Account_Type(models.Model):
	name = models.CharField(max_length=200)

class Account(models.Model):
	number = models.IntegerField(max_length=10)
	name = models.CharField(max_length=200)
	balance = models.DecimalField(decimal_places=2, max_digits=15)
	type = models.ForeignKey(Account_Type, related_name="acount_type")
	
	def __unicode__(self):
		return str(self.name)

	class Meta:
		verbose_name = "Konto"
		verbose_name_plural = "Kontos"

class Accounting(models.Model):
	debitor = models.ForeignKey(Account, related_name="debitor")
	creditor = models.ForeignKey(Account, related_name="creditor")
	ammount = models.DecimalField(decimal_places=2, max_digits=15)
	date = models.DateField("Buchungsatum", default=datetime.date.today)

	def __unicode__(self):
		return str(str(self.debitor.name) + " / " + str(self.creditor.name) + " = " + str(self.ammount))

	class Meta:
		verbose_name = "Buchung"
		verbose_name_plural = "Buchungen"

class Frequency(models.Model):
	frequency = models.IntegerField(max_length=1, null=True)

	def __unicode__(self):
		return str(self.frequency)

	class Meta:
		verbose_name = "Teilnamehäufigkeit"
		verbose_name_plural = "Teilnamehäufigkeiten"

class Duration(models.Model):
	duration = models.DecimalField("Dauer / Minuten", max_digits=5, decimal_places=2, blank=True, null=True)

	def __unicode__(self):
		return str(self.duration)

	class Meta:
		verbose_name = "Dauer"
		verbose_name_plural = "Dauer"


class Charge(models.Model):
	charge = models.DecimalField("Kosten / Stunde", max_digits=5, decimal_places=2, blank=True, null=True)

	def __unicode__(self):
		return u'%s' % (self.charge)

	class Meta:
		verbose_name = "Preis"
		verbose_name_plural = "Preise"


class Contract_Type(models.Model):
	name = models.CharField(max_length=200)
	charge = models.ForeignKey(Charge, default=1)
	duration = models.ForeignKey(Duration, default=1)
	frequency = models.ForeignKey(Frequency, default=1)
	months = models.IntegerField(max_length=2, blank=True, null=True)
	days_a_week = models.IntegerField(max_length=1, blank=True, null=True)

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = "Vertrags Art"
		verbose_name_plural = "Vertrags Arten"


class Discount(models.Model):
	discount = models.CharField("Rabatt", max_length=200)
	name = models.CharField("Name", max_length=200)

	def __unicode__(self):
		return str(self.name) + " " + str(self.discount) + "%"

	class Meta:
		verbose_name = "Rabatt"
		verbose_name_plural = "Rabatte"


class Contract(models.Model):
	number = models.CharField("Vertragsnummer", max_length=200)
	type = models.ForeignKey(Contract_Type)
	start_date = models.DateField("Start Datum", default=datetime.date.today)
	end_date = models.DateField("End Datum", default=datetime.date.today)
	# charge = models.ForeignKey(Charge)
	contact = models.ForeignKey(User, related_name='contract_contact')
	billing_contact = models.ForeignKey(User, related_name='contract_billing_contact')
	# duration = models.ForeignKey(Duration)
	# frequency = models.ForeignKey(Frequency)
	discount = models.ManyToManyField(Discount, blank=True, null=True, related_name='contract_discounts')
	with_tax = models.BooleanField(default=False)
	
	def __unicode__(self):
		return self.number

	def get_frequency_per_week(self):
		return self.type.frequency.frequency / 4

	def calc_tax(self):
		tax = self.calc_summ() * 0.19
		tax = round(tax, 2)

		return tax

	def calc_price(self):
		x = None

		try:
			x = float(self.type.frequency.frequency) * float(self.type.charge.charge)
		except:
			traceback.print_exc(file=sys.stdout)

		return float(x)

	def get_discounts(self):
		discounts = []
		try:
			x = self.calc_price()

			if x != None:
				for discount in self.discount.all():	
					discount_data = {}
					d = x * (float(discount.discount) / 100)
					discount_data["amount"] = float(d)
					discount_data["name"] = discount.name
					discount_data["discount"] = discount.discount
					discounts.append(discount_data)
		except:
			traceback.print_exc(file=sys.stdout)	


		return discounts


	def calc_summ(self):
		summ = None

		try:
			summ = self.calc_price()
			
			discounts = self.get_discounts()

			for discount in discounts:
				summ = summ - discount["amount"]
		except:
			traceback.print_exc(file=sys.stdout)	

		summ = round(summ, 2)

		return summ

	def calc_summ_with_tax(self):
		summ = self.calc_summ()

		if self.with_tax:
			summ = summ + (summ * 0.19)

		summ = round(summ, 2)

		return summ

	def calc_summ_first_month(self):
		registration_fee = 39
		summ = self.calc_summ_with_tax()
		summ = summ + registration_fee
		
		return summ

	def calc_month_difference(self):
		d1 = self.start_date
		d2 = self.end_date 
		delta = 0

		while True:
			mdays = monthrange(d1.year, d1.month)[1]
			print ("mdays " + str(mdays))
			d1 += timedelta(days=mdays)
			if d1 <= d2:
				delta += 1
			else:
				break
		print ("delta " + str(delta))
		return delta

	class Meta:
		verbose_name = "Vertrag"
		verbose_name_plural = "Verträge"


class Bill(models.Model):
	number = models.CharField("Rechnungsnummer", max_length=200)
	person = models.ForeignKey(Person)
	contract = models.ForeignKey(Contract)
	date = models.DateField(null=True)
	paid = models.BooleanField(default=None)
	
	def __unicode__(self):
		return (str(self.number) + " " + str(self.person.name))
	
	class Meta:
		verbose_name = "Rechnung"
		verbose_name_plural = "Rechnungen"

templates/base/base.html
{% include "base/header.html" %}

<body>
	<section id="page">
		{% block content %}
			content
		{% endblock %}
	</section>


{% include "base/footer.html" %}

templates/base/footer.html
		<footer>
			{% block footer %}
			{% endblock %}
		</footer>
	</body>
</html>

templates/base/header_old.html
<!DOCTYPE html>
<html lang="de">
	<head>
		<meta charset="utf-8" />
		<title>Schüler Verwaltung</title>

		<link rel="stylesheet" href="/media/js/lib/fullcalendar/fullcalendar.css"/>
                <link rel="stylesheet" href="/media/js/lib/fullcalendar/fullcalendar.print.css" /media="print" />
                <link rel="stylesheet" href="/media/css/core.css" />

                <!--link rel="stylesheet" href="http://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css"-->

                <script type="text/javascript" src="/media/js/lib/jquery-1.8.2.min.js"></script>
                <script type="text/javascript" src="/media/js/lib/jquery-ui-1.10.2.custom.min.js"></script>
                <script type="text/javascript" src="/media/js/lib/zepto.js"></script>
                <script type="text/javascript" src="/media/js/lib/mustache.js"></script>
				<script type="text/javascript" src="/media/js/lib/jquery.cookie.js"></script>
				<script type="text/javascript" src="/media/js/models/ajax_model.js"></script>
				<script type="text/javascript" src="/media/js/views/calendar_event.js"></script>
                <script type="text/javascript" src="/media/js/globals.js"></script>
                <script type="text/javascript" src="/media/js/slider.js"></script>
                <script type="text/javascript" src="/media/js/module.overlay.js"></script>
                <script type="text/javascript" src="/media/js/module.infobox.js"></script>
                <script type="text/javascript" src="/media/js/module.buttonEvents.js"></script>
                <script type="text/javascript" src="/media/js/calendar.js"></script>
                <script type="text/javascript" src="/media/js/autocomplete.js"></script>
                <script type="text/javascript" src="/media/js/lib/fullcalendar/fullcalendar.js"></script>
                <script type="text/javascript" src="/media/js/lib/fullcalendar/jquery-ui-1.10.2.custom.min.js"></script>
                <script type="text/javascript" src="/media/js/brain.js"></script>
                <script>
                    var csrf_token = "{% csrf_token %}";
                    function csrfSafeMethod(method) {
						// these HTTP methods do not require CSRF protection
						return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
					}
					$.ajaxSetup({
						crossDomain: false, // obviates need for sameOrigin test
						beforeSend: function(xhr, settings) {
							if (!csrfSafeMethod(settings.type)) {
								xhr.setRequestHeader("X-CSRFToken", csrf_token);
							}
						}
					});
				</script>
				{% csrf_token %}
	</head>

templates/base/index.html
{% load staticfiles %}

{% include "base/header_small.html" %}

	<body class="index">
		<section id="page">
			<section id="content" class="clear">
				<div class="left ">
					<span class="title">Organizar</span>
					<br/><img class="logo" src="/media/img/logo.png" />
				</div>
				<div class="right">
					<div class="clear">
						<form action="/" method="post">{% csrf_token %}
							<div style="width: 100%;">
								{% for field in form %}
									<div class="form-field">
										{% if field.errors %}<div class="error"> {% for error in field.errors %}{{ error }}{% endfor %}</div>{% endif %}
										<label class="control-label {% if field.errors %}error{% endif %}">{{ field.label }}</label> 
										{{ field }}
									</div>
								{% endfor %}
							</div>
							<input class="button" type="submit" style="min-height: 40px; line-height: 40px; width: 200px;" name="submit-login" id="submit-login" value="Einloggen" />
						</form>
					</div>
					<a style="margin-top: 0px; font-size: 9px; text-align: left;  margin-left: 14%; display: block;" href="#">Passwort vergessen</a> 
				</div>
			</section>
			<div>
				<p style="font-size: 12px;">
					<br/><br/><br/><br/>
					<a href="http://organizar.de"/>Impressum</a>
				</p>
			</div>
		</section>
<script>
new Vue({
  el: '#app',
  data: {
    message: 'Hello Vue.js!'
  }
})
</script>
<div id="app">
  <p>{{ message }}</p>
</div>

	</body>
</html>

templates/base/loading.html
<html>
<head>
	<link rel="stylesheet" media="all" href="loading.css" />
</head>
	
	<body>
		<div class='solar-syst'>
		<div class='sun'></div>
  <div class='mercury'></div>
  <div class='venus'></div>
  <div class='earth'></div>
  <div class='mars'></div>
  <div class='jupiter'></div>
  <div class='saturn'></div>
  <div class='uranus'></div>
  <div class='neptune'></div>
  <div class='pluto'></div>
  <div class='asteroids-belt'></div>
</div>

	</body>
</html>

templates/base/nosite.html
no site

templates/base/print-old.html
<!-- 
<body>
	<section id="print">
			<div class="box">
				<h3>Stunden drucken</h3>
				<p>Geben Sie hier den Tag an von welchem Sie die Stunden drucken möchten.</p>
				<p>Nach dem Absenden ("klick" auf Termine anzeigen) ganz normal auf Drucken klicken oder "Strg" + "d" drücken.</p>
				<p></p>
				<p></p>
				<form action="/print/" method="post">
					{% csrf_token %}
					<div class="form-field">
						<label for="date">Datum</label><input type="text" id="date" name="date" />
						<input type="submit" value="Termine anzeigen">
					</div>
				</form>
			</div>

			<div class="box">
				<h3>Schüler Liste drucken</h3>
				<p></p>
				<form action="/print/" method="post">
					{% csrf_token %}
					<div class="form-field">
						<input type="hidden" name="print-users" value="True" />
						<input type="submit" value="Schüler Liste anzeigen">
					</div>
				</form>
			</div>

			<div class="box">
				<h3>Vertrag drucken</h3>
				<p></p>
	
				<form action="/print/" method="post">
					{% csrf_token %}
					<div class="search">
						<div class="form-field">
							<input id="trigger-contract-search" type="text" value="Suche" style="padding: 3px;" />
							<div id="contract-search-results" class="search-results"></div>
							<div id="contract-search-values" class="search-values">
								{% for contract in contracts %}
									<div data-type="{{ contract.type }}" data-id="{{ contract.pk }}" draggable="true" class="search-value contract button">
										VNr: {{ contract.number }}<br/>
										Person: {{ contract.contact.first_name }} {{  contract.contact.last_name }} <br/>
										Vertragsart: {{ contract.type }}<br/>
										Zeit: {{ contract.start_date }} bis {{ contract.end_date }}<br/>
									</div>
								{% endfor %}
							</div>
						</div>
					</div>
					{% if contracts %}
						<div class="form-field">
							<select id="id_contract" name="id_contract">
								<option value="">----------------------</option>
								{% for contract in contracts %}
									<option value="{{ contract.pk }}">{% if contract.number %}{{ contract.number }}{% endif %}{{ contract.contact.first_name }} {{  contract.contact.last_name }}</option>
								{% endfor %}
							</select>
						</div>
					{% endif %}
					<br/>
					<div class="form-field">
						<input type="hidden" name="print-contract" value="True" />
						<input type="submit" value="Vertrag drucken">
					</div>
				</form>
			</div>

			<div class="box">
				<h3>Stundenplan drucken</h3>
				<p></p>
	
				<form action="./" method="post">
					<div class="form-field">
						{% csrf_token %}
						{% if users %}
							Benutzer: 
							<select name="user">
							{% for user in users %}
								<option value="{{user.id}}">{{ user.username }}</option>
							{% endfor %}
							</select>
						{% endif %}
						<br/>
						<input type="hidden" name="print-calendar" value="True" />
						<input type="submit" value="Stundenplan anzeigen">
					</div>
				</form>
			</div>
	</section>
</body>
</html>
 -->

templates/base/print_events.html
{% load i18n admin_modify staticfiles %}

<!DOCTYPE html>
<html lang="de">
	<head>
		<meta charset="utf-8" />
		<title>Schüler Verwaltung</title>
		<link rel="stylesheet" href="/media/css/print.css" />


	<script type="text/javascript" src="/media/js/lib/jquery-1.8.2.min.js"></script>
	<script src="/media/js/lib/jquery.maskedinput.min.js" type="text/javascript"></script>
	<script type="text/javascript" src="/media/js/models/user_search_model.js"></script>
	<script type="text/javascript" src="/media/js/bootstrap.js"></script>

<script>
	$(document).ready(function() {
		handlePrint();
		function handlePrint() {
			var contract_type = $("#contract-type");
			if (typeof contract_type != "undefined") {
				var text = contract_type.text();
				text = text.split(" - ")[0];
				contract_type.text(text);
			}

			handlePagebreaks();

			function handlePagebreaks() {
				var events = $(".events");
				$.each(events, function(key, event_list) {
					var height = 0;
					var event_list = $(event_list).find(".event");
					$.each(event_list, function(key, event){
						var event = $(event);
						height = height + parseInt(event.height());
						if (height > 700) {
							event.prepend('<div class="new-page"></div>');
							height = 0;
						}
					});
				});
			}

		var d1 = new Date();
		//d1 = d1.toString('dd.MM.yyyy');
		console.log("d1" + d1);
		var d = d1.getDate();
		var m = d1.getMonth() + 1;
		var y = d1.getFullYear();
		d1 = dateToYMD(d1);
	 	$("#date").mask("99.99.9999", {reverse: true});
			var temp = new Date();
			var month = (1 + temp.getMonth());
			if (month < 10) {
					month = "0" + month
			}
			var dateStr =	 temp.getDate() + "." +
							month + "." +
							temp.getFullYear();
			$("#date").val(dateStr);


			function dateToYMD(date) {
				var d = date.getDate();
				var m = date.getMonth() + 1;
				var y = date.getFullYear();
				return '' + (d <= 9 ? '0' + d : d) + '.' + (m<=9 ? '0' + m : m) + '.' + y;
			}
		}
	});
</script>

	</head>


<body id="print">

	<section id="print-page">


		<!-- PRINT EVENTS BY LEAD -->

		{% if events_by_lead %}
			{% for events in events_by_lead.items %}
				<div class="events">
					<h4>
						{% if events.1.0.lead.first_name and events.1.0.lead.last_name %}
							{{ events.1.0.lead.first_name }} {{ events.1.0.lead.last_name }}
						{% else %}
							{{ events.1.0.lead.username }}
						{% endif %}
					</h4>
					<br/>
					{% for event in events.1 %}
						<div class="event">
							<div class="info"><b>{{ event.date|date:"d.m.Y - D" }} {{ event.start_time | time:"H:i"}} bis {{ event.end_time | time:"H:i"}} Uhr {{ event.lead.last_name }}</b> <span style="margin-left: 50px; display: inline-block;">Fach: {{ event.category }}</span> <span style="float:right;">{{ event.room }}</span></div>
							<ul class="users">
							<table class="users" border="0">
								{% for user in event.users.all %}
									<tr>
										<td class="user-name">
											{% if user.first_name and user.last_name %}
												{{ user.first_name }} 
												{{ user.last_name }}
											{% else %}
												{{ user.username }}
											{% endif %}
										</td>
										<td class="write_space"></td>
									</tr>
								{% endfor %}
							</table>
						</div>
					{% endfor %}

				</div>
				<div class="new-page"></div>
			{% endfor %}



		<!-- PRINT THE CALENDAR OF THE USER -->


		{% elif calendar %}
			<h4>Stundenplan für {{ calendar.user.last_name }} {{ calendar.user.first_name }}</h4>
			<p>Woche {{ calendar.last_monday | date:"D d.m.Y" }} - {{ calendar.next_sunday | date:"D d.m.Y" }}</p>
			<p></p>
			<table>
				{% for event in calendar.events.all %}
					<tr>
						<td style="width: 20%">
							<strong>
								{{ event.date | date:"D d.m.Y" }}<br/>
								{{ event.start_time | time:"H:i" }} - {{ event.end_time | time:"H:i" }}
							</strong>
						</td>
						<td>
							<b>Fach: </b> {{ event.category }}
						</td>
						<td>
							{{ event.room }}
						</td>
						<td>
							<b>Schüler:</b><br/>
							{% for user in event.users.all %}
								{{ user.last_name }} {{ user.first_name }},
							{% endfor %}
						</td>
						<td>
							<b>Lehrer:</b><br/>
							{{ event.lead.last_name }} {{ event.lead.first_name }}
						</td>
					</tr>
				{% endfor %}
			</table>



		<!-- PRINT USER LIST -->

		{% elif users_persons %}
			<h4>Benutzerliste</h4>
			<p>{% now "d.m.Y" %}</p>
			<table class="user-list">
				<th>
					Geschlecht
				</th>
				<th>
					Name
				</th>
				<th>
					Email
				</th>
				<th>
					Adresse
				</th>
				<th>
					Telefon
				</th>
				<th>
					Handy
				</th>
				<th>
					Verfügbarkeit
				</th>
				<th>
					Vertrag
				</th>
				<th>
					Zahlungsart
				</th>
			{% for user, person in users_persons.items %}
				<tr class="user">
					<td>
						{% if person.sex %}
							{% if person.sex == "f" %}
								Frau
							{% else %}
								Herr
							{% endif %}
						{% endif %}
					</td>
					<td>
						{% if user.last_name and user.first_name %}
							{{ user.last_name }} {{ user.first_name }}
						{% else %}
							{{ user }}
						{% endif %}
					</td>
					<td>
						{% if user.email %}
							{{ user.email }}
						{% endif %}
					</td>
					<td>
						{% if person.street %}
							{{ person.street }} 
						{% endif %}
						{% if person.hnr %}
							{{ person.hnr }} <br/>
						{% endif %}
						{% if person.zip %}
							{{ person.zip }}<br/>
						{% endif %}
						{% if person.city %}
							{{ person.city }}
						{% endif %}
					</td>
					<td>
					{% if person.phone %}
						{{ person.phone }}
					{% endif %}
					</td>
					<td>
					{% if person.mobile %}
						{{ person.mobile }}
					{% endif %}
					</td>
					<td>
					{% if person.accessibility %}
						{{ person.accessibility }}
					{% endif %}
					</td>
					<td>
						<dl>
						{% if person.contracts %}
							<dd>
							{% for contract in person.contracts %}
								<i>{{ contract.number }}</i><br/>
								T: {{ contract.type }}<br/>
								B: {{ contract.start_date }}<br/>
								E: {{ contract.end_date }}<br/>
								P: {{ contract.price }} €<br/>
								K: {{ contract.billing_contact }}<br/>
								{% if person.contracts|length > 1 %}
									--<br>
								{% endif %}
							{% endfor %}
							</dd>
						{% else %}
						{% endif %}
						</dl>
					</td>
					<td>
						{% if person.billing_type %}
							{{person.billing_type}}<br/>
						{% endif %}
						{% if person.iban %}
							IBAN<br/>
							{{ person.iban }}
						{% endif %}
					</td>
				</tr>
			{% endfor %}
			<tr>
				<td></td><td></td><td></td><td></td>
				<td></td><td></td><td></td>
				<td><b>Summe: </b>{{ users_persons.summ_billing }} €</td>
				<td></td>
			</tr>
			</table>

		{% elif contract %}

		<h1>Ist jetzt als PDF verfügbar.</h1>

		<!-- PRINT PRINT OPTIONS -->


		{% else %}

			<!-- <a href="/" class="button">Zurück</a> -->
			{% if request.user.is_superuser %}
				<h3>Stunden drucken</h3>
				<p>Geben Sie hier den Tag an von welchem Sie die Stunden drucken möchten.</p>
				<p>Nach dem Absenden ("klick" auf Termine anzeigen) ganz normal auf Drucken klicken oder "Strg" + "d" drücken.</p>
				<p></p>
				<form action="/print/" method="post" target="_blank" class="no-async">
					{% csrf_token %}
					<div class="form-field">
						<label for="date">Datum</label><input type="text" id="date" name="date" />
						<input type="submit" class="button" value="Termine anzeigen">
					</div>
				</form>
	
	<p></p><p></p>
				<h3>Schüler Liste drucken</h3>
				<form action="/print/" method="post" target="_blank" class="no-async">
					{% csrf_token %}
					<div class="form-field">
						<input type="hidden" name="print-users" value="True" />
						<input type="submit" class="button" value="Schüler Liste anzeigen">
					</div>
				</form>
		<!-- 
	<p></p><p></p>
				<h3>Vertrag drucken</h3>
	
				<form action="/print/" method="post" target="_blank" class="no-async">
					{% csrf_token %}
					<div class="form-field">
						<div class="search">
							<input id="trigger-contract-search" type="text" value="Suche" style="padding: 3px;" />
							<div id="contract-search-results" class="search-results"></div>
							<div id="contract-search-values" class="search-values">
								{% for contract in contracts %}
									<div data-type="{{ contract.type }}" data-id="{{ contract.pk }}" draggable="true" class="search-value contract button">
										VNr: {{ contract.number }}<br/>
										Person: {{ contract.contact.first_name }} {{	contract.contact.last_name }} <br/>
										Vertragsart: {{ contract.type }}<br/>
										Zeit: {{ contract.start_date }} bis {{ contract.end_date }}<br/>
									</div>
								{% endfor %}
							</div>
						</div>
					</div>
					<div class="form-field">
						{% if contracts %}
							<select id="id_contract" name="id_contract">
								<option value="">----------------------</option>
								{% for contract in contracts %}
									<option value="{{ contract.pk }}">{% if contract.number %}{{ contract.number }}{% endif %}{{ contract.contact.first_name }} {{	contract.contact.last_name }}</option>
								{% endfor %}
							</select>
						{% endif %}
						<br/>
						<input type="hidden" name="print-contract" value="True" />
						<input type="submit" class="button" value="Vertrag drucken">
					</div>
				</form>
	
	
	 -->
				<p></p><p></p>

				<h3>Stundenplan drucken</h3>
				<p></p>
	
				<form action="/print/" method="post" target="_blank" class="no-async">
					{% csrf_token %}
					<div class="form-field">
						{% if users %}
							Kategorie:
							<select name="category">
								<option value="lead">Lehrer</option>
								<option value="user">Schüler</option>
							</select>
							<br/>
							Benutzer: 
							<input type="text"/>
							<select name="user">
							{% for user in users %}
								<option value="{{user.id}}">{{ user.username }}</option>
							{% endfor %}
							</select>
						{% endif %}
						<br/>
						<input type="hidden" name="print-calendar" value="True" />
						<input type="submit" class="button" value="Stundenplan anzeigen">
					</div>
				</form>
			{% else %}
				<h3>Stundenplan für die aktuelle Woche drucken für {{ request.user.first_name }} {{ request.user.last_name }}</h3>
				<form action="/print/" method="post" target="_blank" class="no-async">
					{% csrf_token %}
					<div class="form-field">
						<input type="hidden" name="category" value="lead" />
						<input type="hidden" name="user" value="{{ request.user.id }}" />
						<input type="hidden" name="print-calendar" value="True" />
						<input type="submit" class="button" value="Stundenplan anzeigen">
					<div class="form-field">
				</form>
			{% endif %}
			
		{% endif %}
	</section>
</body>
</html>