_mail/urls.py
from django.conf.urls import url
from _mail import views 

urlpatterns = [ 
  # The home view ('/tutorial/') 
  url(r'^m/$', views.home, name='home'), 
  # Explicit home ('/tutorial/home/') 
  url(r'^m/home/$', views.home, name='home'), 
  # Redirect to get token ('/tutorial/gettoken/')
  url(r'^m/gettoken/$', views.gettoken, name='gettoken'),
  # Mail view ('/tutorial/mail/')
  url(r'^m/mail/$', views.mail, name='mail'),
]

_todo/urls.py
from django.conf.urls import patterns, include, url
from _todo.views import handle_todo, task_control, delete_todo
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^task_control/$', task_control, name='task_control'),
	url(r'^handle_todo/$', handle_todo, name='handle_todo'),
	url(r'^handle_todo/(?P<todo_id>.*)/$', handle_todo, name='handle_todo'),
	url(r'^delete_todo/(?P<todo_id>.*)/$', delete_todo, name='delete_todo'),
) 

_billing/models.py
# coding=UTF-8

from calendar import monthrange
from datetime import timedelta
import datetime
import sys 
import traceback

from django.contrib.auth.models import User
from django.db import models

from _user.models import Person


# #CHANGED
# class Product(models.Model):
# 	name = models.CharField(max_length=200)
# 	price = models.DecimalField("Preis", max_digits=15, decimal_places=2, blank=True, null=True)
class Account_Type(models.Model):
	name = models.CharField(max_length=200)

class Account(models.Model):
	number = models.IntegerField(max_length=10)
	name = models.CharField(max_length=200)
	balance = models.DecimalField(decimal_places=2, max_digits=15)
	type = models.ForeignKey(Account_Type, related_name="acount_type")
	
	def __unicode__(self):
		return str(self.name)

	class Meta:
		verbose_name = "Konto"
		verbose_name_plural = "Kontos"

class Accounting(models.Model):
	debitor = models.ForeignKey(Account, related_name="debitor")
	creditor = models.ForeignKey(Account, related_name="creditor")
	ammount = models.DecimalField(decimal_places=2, max_digits=15)
	date = models.DateField("Buchungsatum", default=datetime.date.today)

	def __unicode__(self):
		return str(str(self.debitor.name) + " / " + str(self.creditor.name) + " = " + str(self.ammount))

	class Meta:
		verbose_name = "Buchung"
		verbose_name_plural = "Buchungen"

class Frequency(models.Model):
	frequency = models.IntegerField(max_length=1, null=True)

	def __unicode__(self):
		return str(self.frequency)

	class Meta:
		verbose_name = "Teilnamehäufigkeit"
		verbose_name_plural = "Teilnamehäufigkeiten"

class Duration(models.Model):
	duration = models.DecimalField("Dauer / Minuten", max_digits=5, decimal_places=2, blank=True, null=True)

	def __unicode__(self):
		return str(self.duration)

	class Meta:
		verbose_name = "Dauer"
		verbose_name_plural = "Dauer"


class Charge(models.Model):
	charge = models.DecimalField("Kosten / Stunde", max_digits=5, decimal_places=2, blank=True, null=True)

	def __unicode__(self):
		return u'%s' % (self.charge)

	class Meta:
		verbose_name = "Preis"
		verbose_name_plural = "Preise"


class Contract_Type(models.Model):
	name = models.CharField(max_length=200)
	charge = models.ForeignKey(Charge, default=1)
	duration = models.ForeignKey(Duration, default=1)
	frequency = models.ForeignKey(Frequency, default=1)
	months = models.IntegerField(max_length=2, blank=True, null=True)
	days_a_week = models.IntegerField(max_length=1, blank=True, null=True)

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = "Vertrags Art"
		verbose_name_plural = "Vertrags Arten"


class Discount(models.Model):
	discount = models.CharField("Rabatt", max_length=200)
	name = models.CharField("Name", max_length=200)

	def __unicode__(self):
		return str(self.name) + " " + str(self.discount) + "%"

	class Meta:
		verbose_name = "Rabatt"
		verbose_name_plural = "Rabatte"


class Contract(models.Model):
	number = models.CharField("Vertragsnummer", max_length=200)
	type = models.ForeignKey(Contract_Type)
	start_date = models.DateField("Start Datum", default=datetime.date.today)
	end_date = models.DateField("End Datum", default=datetime.date.today)
	# charge = models.ForeignKey(Charge)
	contact = models.ForeignKey(User, related_name='contract_contact')
	billing_contact = models.ForeignKey(User, related_name='contract_billing_contact')
	# duration = models.ForeignKey(Duration)
	# frequency = models.ForeignKey(Frequency)
	discount = models.ManyToManyField(Discount, blank=True, null=True, related_name='contract_discounts')
	with_tax = models.BooleanField(default=False)
	
	def __unicode__(self):
		return self.number

	def get_frequency_per_week(self):
		return self.type.frequency.frequency / 4

	def calc_tax(self):
		tax = self.calc_summ() * 0.19
		tax = round(tax, 2)

		return tax

	def calc_price(self):
		x = None

		try:
			x = float(self.type.frequency.frequency) * float(self.type.charge.charge)
		except:
			traceback.print_exc(file=sys.stdout)

		return float(x)

	def get_discounts(self):
		discounts = []
		try:
			x = self.calc_price()

			if x != None:
				for discount in self.discount.all():	
					discount_data = {}
					d = x * (float(discount.discount) / 100)
					discount_data["amount"] = float(d)
					discount_data["name"] = discount.name
					discount_data["discount"] = discount.discount
					discounts.append(discount_data)
		except:
			traceback.print_exc(file=sys.stdout)	


		return discounts


	def calc_summ(self):
		summ = None

		try:
			summ = self.calc_price()
			
			discounts = self.get_discounts()

			for discount in discounts:
				summ = summ - discount["amount"]
		except:
			traceback.print_exc(file=sys.stdout)	

		summ = round(summ, 2)

		return summ

	def calc_summ_with_tax(self):
		summ = self.calc_summ()

		if self.with_tax:
			summ = summ + (summ * 0.19)

		summ = round(summ, 2)

		return summ

	def calc_summ_first_month(self):
		registration_fee = 39
		summ = self.calc_summ_with_tax()
		summ = summ + registration_fee
		
		return summ

	def calc_month_difference(self):
		d1 = self.start_date
		d2 = self.end_date 
		delta = 0

		while True:
			mdays = monthrange(d1.year, d1.month)[1]
			print ("mdays " + str(mdays))
			d1 += timedelta(days=mdays)
			if d1 <= d2:
				delta += 1
			else:
				break
		print ("delta " + str(delta))
		return delta

	class Meta:
		verbose_name = "Vertrag"
		verbose_name_plural = "Verträge"


class Bill(models.Model):
	number = models.CharField("Rechnungsnummer", max_length=200)
	person = models.ForeignKey(Person)
	contract = models.ForeignKey(Contract)
	date = models.DateField(null=True)
	paid = models.BooleanField(default=None)
	
	def __unicode__(self):
		return (str(self.number) + " " + str(self.person.name))
	
	class Meta:
		verbose_name = "Rechnung"
		verbose_name_plural = "Rechnungen"

_todo/models.py
# coding=UTF-8

from django.db import models
from django.contrib.auth.models import User
from _calendar.models import Event

class Todo_Category(models.Model):
	name = models.CharField("Name", max_length=2000)

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = "Todo Kategorie"
		verbose_name_plural = "Todo Kategorien"

class Todo_Priority(models.Model):
	name = models.CharField("Name", max_length=2000)

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = "Todo Priorität"
		verbose_name_plural = "Todo Priorität"

class Todo(models.Model):
	text = models.CharField("Text", max_length=2000)
	users = models.ManyToManyField(User, blank=True, null=True, related_name='users_of_todo')
	event = models.ForeignKey(Event, blank=True, null=True)
	done = models.NullBooleanField(blank=True, null=True)
	category = models.ForeignKey(Todo_Category)
	priority = models.ForeignKey(Todo_Priority)
	# TODO extend by date

	def __unicode__(self):
		return self.text

	class Meta:
		verbose_name = "Todo"
		verbose_name_plural = "Todos"

_user/models.py
# coding: utf-8

from django.db import models
from django.contrib.auth.models import User

SEX = (
	('m', 'Herr'),
	('f', 'Frau'),
)



# class User(User):
# 	
# 	def __unicode__(self):
# 		name = self.name
# 		print ("!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
# 		if self.last_name and self.first_name:
# 			name = self.last_name + " " + self.first_name
# 		return name
# 
# 	class Meta:
# 		ordering = ['last_name']
# 		verbose_name = "Benutzer"
# 		verbose_name_plural = "Benutzer"

class Subject(models.Model):
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return self.name

	class Meta:
		ordering = ['name']
		verbose_name = "Fach"
		verbose_name_plural = "Fächer"

class Grade(models.Model):
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = "Klasse"
		verbose_name_plural = "Klassen"

class School(models.Model):
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return self.name

	class Meta:
		ordering = ['name']
		verbose_name = "Schule"
		verbose_name_plural = "Schulen"

class Person(models.Model):
	sex = models.CharField("Geschlecht", max_length=1, choices=SEX, blank=True, null=True)
	birthday = models.DateField("Geburtstag", blank=True, null=True) # new
	street = models.CharField("Strasse", max_length=200, blank=True, null=True)
	hnr = models.CharField("Hausnummer", max_length=10, blank=True, null=True)
	zip = models.IntegerField("PLZ", max_length=8, blank=True, null=True)
	city = models.CharField("Stadt", max_length=200, blank=True, null=True)
	country = models.CharField("Land", max_length=200, blank=True, null=True) # new
	phone = models.CharField("Telefon", max_length=200, blank=True, null=True)
	mobile = models.CharField("Handy", max_length=200, blank=True, null=True)
	accessibility = models.CharField("Mögliche Termine oder Zeiten wo unmöglich gehen.", max_length=600, blank=True, null=True) # new
	user = models.OneToOneField(User)

	def __unicode__(self):
		return str(self.mobile)
	
	def get_user(self):
		return self.user

	class Meta:
		verbose_name = "Benutzer"
		verbose_name_plural = "Benutzer"

class Child_Contact(models.Model):
	grade = models.ForeignKey(Grade, blank=True, null=True) # new
	school = models.ForeignKey(School, blank=True, null=True) # new
	person = models.OneToOneField(Person)

	def __unicode__(self):
		return self.child.street

	class Meta:
		verbose_name = "Schüler"
		verbose_name_plural = "Schüler"

class Billing_Type(models.Model):
	name = models.CharField(max_length=200)

	def __unicode__(self):
		return self.name

	class Meta:
		verbose_name = "Rechnungstyp"
		verbose_name_plural = "Rechnungstypen"

class Billing_Contact(models.Model):
	knr = models.CharField(max_length=200, blank=True, null=True)
	blz = models.CharField(max_length=200, blank=True, null=True)
	iban = models.CharField(max_length=200, blank=True, null=True)
	iban = models.CharField(max_length=200, blank=True, null=True)
	billing_type = models.ForeignKey(Billing_Type, blank=True, null=True)
	person = models.OneToOneField(Person)

	def __unicode__(self):
		return self.person.user.last_name

	class Meta:
		verbose_name = "Rechnungsadresse"
		verbose_name_plural = "Rechnungsadressen"

_billing/forms.py
# coding=UTF-8
from django import forms
from _billing.models import Contract, Contract_Type
from django.contrib.auth.models import User
from django.forms import ModelForm


class Contract_Form(ModelForm):
	number = forms.CharField(widget=forms.HiddenInput)
	class Meta:
		model = Contract
		exclude = []

class Contract_Type_Form(ModelForm):

	class Meta:
		model = Contract_Type
		exclude = []

_todo/forms.py
from django.forms import ModelForm
from django import forms
from _todo.models import Todo
from django.contrib.auth.models import User

CHOICES=[
         ("False",'Offen'),
	 ("True",'Erledigt')]

class Todo_Form(ModelForm):
	text = forms.CharField( widget=forms.Textarea )


	class Meta:
		model = Todo
		exclude = []

	def __init__(self, *args, **kwargs):
		super(ModelForm, self).__init__(*args, **kwargs)
		self.fields['users'].queryset = User.objects.order_by('last_name')

_user/forms.py
# coding=UTF-8
from django import forms
from _user.models import Person, Billing_Contact
from django.contrib.auth.models import User
from django.forms import ModelForm

class Person_Form(ModelForm):
	accessibility = forms.CharField(label="Mögliche / unmögiche Termine in der Woche.", required=False, widget=forms.Textarea )
	class Meta:
		model = Person
		#fields = ['pub_date', 'headline', 'content', 'reporter']
		#exclude = ["user"]
		widgets = {'user': forms.HiddenInput}
		exclude = []

class Billing_Contact_Form(ModelForm):
	class Meta:
		model = Billing_Contact
		widgets = {'person': forms.HiddenInput}
		exclude = []
		#exclude = ["person"]

class User_Form(ModelForm):
	id = forms.IntegerField(widget=forms.HiddenInput)
	first_name = forms.CharField(label="Vorname", error_messages={'required': 'Bitte geben Sie den Vornamen ein!'})
	last_name = forms.CharField(label="Nachname", error_messages={'required': 'Bitte geben Sie den Nachnamen ein!'})
	email = forms.EmailField(label="Email", error_messages={'required': 'Bitte geben Sie eine gültige Emailadresse ein! z.B. max_mustermann@gmx.de'})

	class Meta:
		model = User
		exclude = ["password", "is_superuser", "is_staff", "date_joined", "user_permissions", "last_login", "is_active"]#"groups",

#	def __init__(self, *args, **kwargs):
#		super(User_Form, self).__init__(*args, **kwargs)
#		self.helper = FormHelper()
#		self.helper.form_id = 'id-exampleForm'
#		self.helper.form_class = 'blueForms'
#		self.helper.form_method = 'post'
#		self.helper.form_action = 'submit_survey'
 #       	self.helper.layout = Layout(
#            		Fieldset(
#				'Benutzer',
#				'email',
#				'favorite_number',
#				'favorite_color',
#				HTML("""
#					<p>We use notes to get better, <strong>please help us {{ username }}</strong></p>
#				"""),
#				'favorite_food',
#				'notes'
#            		),
#			ButtonHolder(
#				Submit('submit', 'Submit', css_class='button white')
#			)
#        	)

_todo/views.py
from _todo.forms import Todo_Form
from django.template import RequestContext, loader
from django.http import HttpResponse, HttpResponseNotFound
from _todo.models import Todo
from _utils.template_utils import set_session_var
from django.contrib.auth.decorators import login_required

@login_required(login_url='/')
def task_control(request):
	template = loader.get_template('_task/control.html')	
	tasks = Todo.objects.all()

	context = RequestContext(request, {
		'tasks': tasks,
	})

	return HttpResponse(template.render(context))

@login_required(login_url='/')
def delete_todo(request, todo_id=None):

	if todo_id != None:
		try:
			todo = Todo.objects.get(id=todo_id)
			todo.delete()
			return HttpResponse()
		except:
			print "could not delete todo " + str(todo_id)
			return HttpResponseNotFound()

@login_required(login_url='/')
def handle_todo(request, todo_id=None):
	form_type = "todo"
	form = Todo_Form(initial={'done': 0})
	template = loader.get_template('base/placeholder.html')	
	print "~~~~~~~~~~~~ HANDLE TODO ~~~~~~~~~~~~"
	info = ""

	if request.method == 'POST':
		try:
			todo = Todo.objects.get(pk=todo_id)
			form = Todo_Form(request.POST, instance=todo)
		except:		
			form = Todo_Form(request.POST)

		if form.is_valid():
			form.save()
			#return HttpResponseRedirect('/calendar')
			print "todo saved"
			info = "Todo gespeichert!"
		else:
			info = "Todo NICHT gespeichert!"

	elif todo_id != None:
		try:
			todo = Todo.objects.get(pk=todo_id)
			form = Todo_Form(instance=todo)
		except:
			print "error could not find todo for id " + str(todo_id)

	context = RequestContext(request, {
		'form': form,
		"info" : info,
		"form_type"   : form_type,
	})
	

	return HttpResponse(template.render(context))

templates/base/forms/contract.html
{% if contract_form %}
<section id="page">
<div id="content">
	<script>
	
		$(document).ready(function() {
			var add_user_buttons = $("#add-new-contact, #add-new-billing-contact");

			add_user_buttons.click(function() {
				var button = $(this);
				var wrapper = $(this).parent();

				button.addClass("hidden");
				wrapper.find(".new-user-form").removeClass("hidden");
				wrapper.find(".user-search").addClass("hidden");

				wrapper.find(".back").click(function() {
					button.removeClass("hidden");
					wrapper.find(".new-user-form").addClass("hidden");
					wrapper.find(".user-search").removeClass("hidden");
				});
			});

			// show contract id if existing
			var contract_id_field = $("#id_number");
			var contract_id = contract_id_field.val();
			if (typeof contract_id != "undefined" && contract_id != "") {
				contract_id_field.parent().prepend(contract_id);
			}

			//show and set billing contact if recently created
			var user_id = $("#id_id").attr("value");
			if (typeof user_id != "undefined" && user_id != "") {
				console.log("USER ID IS NOT UNDEFINED", user_id);
				var select_options = $("#id_billing_contact").find("option");
				select_options.attr('selected', false);
				$.each(select_options, function(key, option) {
					var option = $(option);
					var value = option.val();
					if (value == user_id) {
						var wrapper = option.parent().parent();
						option.attr('selected', true);
						console.log("setting true to ", option);
						//wrapper.css("display", "block");
						//wrapper.html("<div class=\"hidden\">" + wrapper.html() + "</div>");
						//wrapper.prepend("<label>Rechnungsadresse:</label><input type=\"text\" value=\"" + option.text() + "\"readonly=\"readonly\"/>");

						return false;
					}
				});
			}

			var selected_billing_options = $("#id_billing_contact").find("option:selected");
			show_select_option(selected_billing_options, null, "Vertragspartner", 'id_billing_contact');

			// show contact if set 
			var selected_options = $("#id_contact").find("option:selected");
			show_select_option(selected_options, null, "Schüler", 'id_contact');

			function show_select_option(selected_options, value, label, id) {
				$.each(selected_options, function(key, option) {
					var option = $(option);
					var wrapper = option.parent().parent();
					var text = "";
					var newID = "target_" + id
					var errorDiv = wrapper.find(".error");

					wrapper.css("display", "block");
					wrapper.html("<div class=\"hidden\">" + wrapper.html() + "</div>");

					if (typeof value != "undefined" && value != null && value != "") {
						text = value;
					}
					else {
						if (option.text() != "---------") {
							text = option.text();
							$.cookie(id, text);
						}
					}

					//wrapper.prepend(errorDiv[0].outerHTML + "<label>" + label + ":</label><input id=\"" + newID + "\" type=\"text\" value=\"" + text + "\"readonly=\"readonly\"/>");
				});
			}
		});

	</script>
	<style>
		.right #user-id {
			display: none;
		}
		#overlay-content #content input[type="checkbox"] {
			display: block !important;
		}
	</style>

	<div>
		<form action="{{ form_action }}" method="post" data-default-action="{{ request.get_full_path }}">
			<section class="two-col">
	
				<div class="left">
					<h3>Schüler</h3>
	
					<div class="user-search">
						<label for="search-user">Benutzer Suchen</label>
						<input type="text" name="search-user" id="add-contract-contact" class="search-user" />
						<div class="results"></div>
					</div>
				</div>
	
				<div class="right">
					<h3>Rechnungskontakt</h3>
					{% if show_new_user %}
						<div class="button" id="add-new-billing-contact">Rechnungskontakt +</div>
	
						<div class="user-search">
							<label for="search-user">Benutzer Suchen</label>
							<input type="text" name="search-user" id="add-contract-billing-contact" class="search-user" />
							<div class="results"></div>
						</div>
	
						<div class="hidden new-user-form">
							<div class="button back">zurück zur Benutzersuche</div>
							{% include 'base/forms/person_for_contract.html' %}
						</div>
					{% else %}
						{% include 'base/forms/person_for_contract.html' %}
					{% endif %}
				</div>
			</section>

			<div style="margin: 0 0 0 0; width: 100%;">
				<h3>Vertragsdaten</h3>
				<div class="form-field">
					{% csrf_token %}
				</div>
				
				<h4>Vertragspartner</h4>
				<p>{% get_user_name contract_form "contact" %}</p>
				<h4>Gläubiger</h4>
				<p>{% get_user_name contract_form "billing_contact" %}</p>
				
				<br/></br>
				
				{% for field in contract_form %}
					<div class="form-field">
						{% if field.errors %}<div class="error"> {% for error in field.errors %}{{ error }}{% endfor %}</div>{% endif %}
						<label class="control-label {% if field.errors %}error{% endif %}">{{ field.label }}</label> 
						{{ field }}
					</div>
				{% endfor %}
				
				<div class="form-field">
					<input class="button" type="submit" value="Speichern" />
				</div>
			</div>

			<div class="user-search-values hidden">
				{% for user in all_users %}
					<div data-cat="{% for category in user.category.all %}{{ category.name }}{% endfor %}" data-id="{{ user.pk }}" class="search-value user button" data-name="{{ user.first_name }} {{ user.last_name }}">
						{{ user.first_name }} {{ user.last_name }}
					</div>
				{% endfor %}
			</div>
		</form>
	</div>
{% else %}
	<h1>nope</h1>
{% endif %}
</div>
</section>

templates/base/forms/edit_group.html
<div id="content">
	{% if info %}
		<div class="info">{{ info }}</div>
	{% endif %}
	{% if event_to_delete %}
			
		<h4>Diese Stunden fallen aus dem Ramen.</h4>
		<ul>
			{% for event in event_to_delete %}
				<li>
					{{ event.date |date:"d.m.Y" }} {{ event.date |time:"g:i" }} {{ event.name }}
					<a class="button" target="_blank" href="/event/{{ event.id }}/edit/" data-divclassorid="#content">
						<img src="/media/img/edit.png" alt="edit"/>
					</a>
					<a class="button ajax event-group delete" href="/event/{{ event.id }}/delete/">
						<img src="/media/img/delete.png" alt="delete"/>
					</a>
				</li>
			{% endfor %}
		</ul>
	{% endif %}
	<br/><br/><br/>
	<h4>Gruppe bearbeiten</h4>
	{% if group_form %}
	
	
		<div>
			<form action="./" method="post" data-default-action="{{ request.get_full_path }}">
				{% csrf_token %}
				{{ group_form.as_p }}
				<input class="button" type="submit" value="Speichern" />
			</form>
		</div>
	
	{% endif %}
		{% if form %}
			<form action="./" method="post" data-default-action="{{ request.get_full_path }}">
		{% csrf_token %}
	    {{ form.non_field_errors }}
	    <div class="form-field">
	        {{ form.name.errors }}
	        <label for="id_name">Name <br/> Beschreibung</label>
	        {{ form.name }}
	    </div>
		<div class="form-field">
			{{ form.date.errors }}
			<label for="id_date">Datum:</label>
			{{ form.date }}
		</div>
	    <div class="form-field">
	        {{ form.start_time.errors }}
	        <label for="id_start_time">Beginn: </label>
	        {{ form.start_time }}
	    </div>
		<div class="form-field">
			{{ form.end_time.errors }}
			<label for="id_end_time">Ende:</label>
			{{ form.end_time }}
		</div>
		<div class="form-field">
			{{ form.room.errors }}
			<label for="id_room">Raum:</label>
			{{ form.room }}
		</div>
	
		<div class="form-field">
				<div class="search">
					<input class="trigger-search" type="text" value="Suche" style="padding: 3px;" autocomplete="off" />
					<div class="search-results"></div>
					<div class="search-values">
						{% for instance in form.users.field.queryset %}
							<div data-cat="employee" data-id="{{ instance.pk }}" draggable="true" class="search-value user button">
								<span class="text">{{ instance.first_name }} {{ instance.last_name }}</span>
							</div>
						{% endfor %}
					</div>
				</div>
			<label for="id_persons">Schüler:</label>
			{{ form.users }}
		</div>
		<div class="form-field">
			{{ form.category.errors }}
			<label for="id_category">Fach:</label>
			{{ form.category }}
		</div>
		
		<div class="form-field">
			{{ form.lead.errors }}
			<label for="id_lead">Lehrer:</label>
			{{ form.lead }}
		</div>
		
		<p><input class="button" type="submit" value="Absenden" /></p>
	</form>
	{% endif %}
</div>

templates/base/forms/event.html
<div id="content">

<div id="event-form-wrapper" >
	<h2>Termin</h2>
	<form id="event-form" action="./" method="post" data-callback="Calendar_View.newEventFormCallback()" data-default-action="{{ request.get_full_path }}">
		{% csrf_token %}

		<div class="form-field" style="display: none;">
			{{ form.non_field_errors }}
			{{ form.name.errors }}
			<label for="id_name">Name <br/> Beschreibung</label>
			{{ form.name }}
		</div>
		<div class="form-field">
			{{ form.date.errors }}
			<label for="id_date">Datum:</label>
			{{ form.date }}
		</div>
		<div class="form-field">
			{{ form.start_time.errors }}
			<label for="id_start_time" class="datepicker-time">Beginn:</label>
			{{ form.start_time }}
		</div>
		<div class="form-field">
			{{ form.end_time.errors }}
			<label for="id_end_time" class="datepicker-time">Ende:</label>
			{{ form.end_time }}
		</div>
		<div class="form-field">
			{{ form.room.errors }}
			<label for="id_room">Raum:</label>
			{{ form.room }}
		</div>
		<div class="form-field">
			<div class="search">
				<input class="trigger-search" type="text" value="Suche" style="padding: 3px;" autocomplete="off" />
				<div class="search-results"></div>
				<div class="search-values">
					{% for instance in form.users.field.queryset %}
						<div data-cat="employee" data-id="{{ instance.pk }}" draggable="true" class="search-value user button">
							<span class="text">{{ instance.first_name }} {{ instance.last_name }}</span>
						</div>
					{% endfor %}
				</div>
			</div>
		</div>
		<div class="form-field">
			{{ form.users.errors }}
			<label for="id_users">Schüler:</label>
			<div>
			{{form.users}}
			</div>
	
		</div>
		<div class="form-field">
			{{ form.category.errors }}
			<label for="id_category">Fach:</label>
			{{ form.category }}
		</div>
		<div class="form-field">
			{{ form.lead.errors }}
			<label for="id_lead">Lehrer:</label>
			{{ form.lead }}
		</div>
		<div class="form-field">
			{{ form.event_group.errors }}
			<div class="hidden">{{ form.event_group }}</div>
			<label for="id_event_group">Termin Serie:
			</label>
			<!-- 
			<a id="edit-event-group" class="button" href="/edit/event_group/{% if form.initial.id %}{{ form.initial.id }}{% else %}new{% endif %}/{% if form.event_group.value %}{{ form.event_group.value }}{% else %}new{% endif %}/">
				<img src="/media/img/edit.png" alt="edit"/>
			</a>
			-->
			<a id="new-event-group" class="button" href="/add/event_group/{% if form.initial.id %}{{ form.initial.id }}{% else %}new{% endif %}/">
				<strong>neu</strong>
			</a>
		</div>
		<div class="form-field">
			<input class="button" type="submit" value="Absenden" />
		</div>
	</form>
</div>
</div>

templates/base/forms/user_comment.html
{% if form %}
	<div id="comment-form">	
		<form action="./" method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<input class="button" type="submit" value="Speichern" />
		</form>
	</div>
{% endif %}